-- Backend Phase 1A — BF1A.5
-- Organization invites — the simpler of the two onboarding mechanisms
-- (chosen over invite-by-email per the brief: no SMTP dependency, no
-- transactional email provider needed).
--
-- An org admin / owner generates a short code via the `create_invite`
-- RPC. They share the code out of band (Slack, email, etc.). The
-- recipient signs up, then redeems the code via the `accept_invite`
-- RPC. Both functions run as `security definer` and enforce their
-- own authorization, so the table itself doesn't need permissive
-- RLS — direct access is fenced off.

create table if not exists public.organization_invites (
  id              uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations on delete cascade,
  code            text not null unique,
  org_role        org_role not null default 'member',
  created_by      uuid references auth.users on delete set null,
  created_at      timestamptz not null default now(),
  expires_at      timestamptz,
  accepted_at     timestamptz,
  accepted_by     uuid references auth.users on delete set null
);

create index if not exists organization_invites_organization_id_idx
  on public.organization_invites (organization_id);
create index if not exists organization_invites_code_idx
  on public.organization_invites (code) where accepted_at is null;

comment on table public.organization_invites is
  'Short codes that grant a user membership to an organization. Generated by org admins/owners via create_invite(). Redeemed via accept_invite(). Direct table access is denied; the RPCs do all the work.';

-- ─── RLS ────────────────────────────────────────────────────────────
alter table public.organization_invites enable row level security;

-- Admins / owners can list outstanding invites for their org so they
-- can revoke or audit them. Nobody else gets direct read access —
-- the accept_invite() RPC handles redemption without needing a
-- client side select.
drop policy if exists organization_invites_select_admin
  on public.organization_invites;
create policy organization_invites_select_admin
  on public.organization_invites for select
  using (public.is_org_admin(organization_id));

-- Admins / owners can revoke an invite by deleting the row. Insert
-- is denied to all clients; create_invite() is the only path.
drop policy if exists organization_invites_delete_admin
  on public.organization_invites;
create policy organization_invites_delete_admin
  on public.organization_invites for delete
  using (public.is_org_admin(organization_id));

-- ─── RPC: create_invite ─────────────────────────────────────────────
-- Returns the generated code (random 12 char base32 string). Only
-- admins / owners of the target org can call it; others get a clean
-- 'not authorized' error.

create or replace function public.create_invite(
  org_id    uuid,
  role      org_role default 'member',
  ttl_hours int default 168           -- one week default
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  generated_code text;
begin
  if auth.uid() is null then
    raise exception 'not authenticated';
  end if;
  if not public.is_org_admin(org_id) then
    raise exception 'not authorized to create invites for this organization';
  end if;
  if ttl_hours < 1 or ttl_hours > 24 * 30 then
    raise exception 'ttl_hours out of range (1 to 720)';
  end if;

  -- 12 character base32 ish code. Crockford alphabet (no 0/O/I/L
  -- confusion). Take 8 random bytes -> 12 chars after base32
  -- encoding. Retry on the very unlikely uniqueness collision.
  loop
    generated_code := upper(replace(encode(gen_random_bytes(8), 'base32'), '=', ''));
    generated_code := substring(generated_code from 1 for 12);
    begin
      insert into public.organization_invites (organization_id, code, org_role, created_by, expires_at)
      values (org_id, generated_code, role, auth.uid(), now() + (ttl_hours || ' hours')::interval);
      exit;
    exception
      when unique_violation then null;  -- collision, retry
    end;
  end loop;

  return generated_code;
end$$;

revoke all on function public.create_invite(uuid, org_role, int) from public;
grant execute on function public.create_invite(uuid, org_role, int) to authenticated;

-- ─── RPC: accept_invite ─────────────────────────────────────────────
-- Validates the code, inserts the membership, marks the invite
-- accepted. Returns the org id + assigned role so the caller can
-- route the user into the org.

create or replace function public.accept_invite(invite_code text)
returns table (organization_id uuid, org_role org_role)
language plpgsql
security definer
set search_path = public
as $$
declare
  invite_row public.organization_invites;
begin
  if auth.uid() is null then
    raise exception 'not authenticated';
  end if;

  -- Trim + uppercase so users pasting with whitespace still hit.
  invite_code := upper(trim(invite_code));

  select * into invite_row from public.organization_invites
    where code = invite_code
      and accepted_at is null
      and (expires_at is null or expires_at > now())
    limit 1;

  if invite_row.id is null then
    raise exception 'invite not found or expired';
  end if;

  -- Insert the membership. If the user is already a member of this
  -- org (rare race), the on conflict do nothing path makes accept
  -- idempotent rather than throwing.
  insert into public.organization_members (organization_id, user_id, org_role)
  values (invite_row.organization_id, auth.uid(), invite_row.org_role)
  on conflict (organization_id, user_id) do nothing;

  update public.organization_invites
    set accepted_at = now(),
        accepted_by = auth.uid()
    where id = invite_row.id;

  return query select invite_row.organization_id, invite_row.org_role;
end$$;

revoke all on function public.accept_invite(text) from public;
grant execute on function public.accept_invite(text) to authenticated;
